name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    name: PHPStan & Nette Tester
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nette

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: json, tokenizer
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPStan Analysis
        run: vendor/bin/phpstan analyse app tests --level=5

      - name: Run Nette Tester
        run: vendor/bin/tester tests -s
